# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: unicode
  database: hello_react_on_rails_development
  pool: 5
  username: you
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: hello_react_on_rails_test
  pool: 5
  username: you
  password:
  timeout: 5000
